import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {moduleUrl} from './profile-loader.mjs';
const m=await import(moduleUrl('lib/basketball-efficiency.ts')),n=await import(moduleUrl('lib/nba.ts')),w=await import(moduleUrl('lib/wnba.ts')),presentation=await import(moduleUrl('lib/nba-analysis.ts'));
const now=Date.parse('2026-09-29T16:00:00Z'),read=p=>JSON.parse(readFileSync(p,'utf8'));
function fixture(league){const lower=league.toLowerCase(),parse=league==='NBA'?n.parseNbaEvents:w.parseWnbaEvents,ids=league==='NBA'?['2','5']:['16','20'],game=parse(read(`tests/fixtures/${lower}/${league==='NBA'?'future':'day-20260930'}.json`)).find(g=>g.id===(league==='NBA'?'401898392':'401918019')),history=ids.flatMap(id=>[2,3].flatMap(p=>parse(read(`tests/fixtures/${lower}/team-${id}-2026-${p}.json`),id))),raw=read(`tests/fixtures/basketball-efficiency/${lower}-boxes.json`),games=[...new Map(ids.flatMap(id=>m.efficiencyHistory(game,history,id,league,now)).map(g=>[g.id,g])).values()],boxes=games.map(g=>m.parseEfficiencyBox(raw[g.id],g,league));return {game,history,boxes,raw,games};}
const nba=fixture('NBA'),wnba=fixture('WNBA');
const metrics=(patch={})=>({games:20,ortg:110,drtg:110,pace:100,threePct:.35,threeRate:.4,ftRate:.25,observations:Array.from({length:20},(_,i)=>({offense:110+(i%2?4:-4),defense:110+(i%2?5:-5),three:.35+(i%2?.04:-.04),freeThrows:.25+(i%2?.03:-.03),margin:i%2?10:-10})),...patch});
test('weights normalize to 100%, reject zero/non-finite/out-of-range and share keys for equivalent ratios',()=>{assert.deepEqual(m.normalizedWeights([20,20,20,20,20]),[.2,.2,.2,.2,.2]);assert.equal(m.weightKey([20,20,20,20,20]),m.weightKey([10,10,10,10,10]));for(const value of ['0,0,0,0,0','1,2,3','NaN,20,20,20,20','101,0,0,0,0',',20,20,20,20','-1,20,20,20,20'])assert.throws(()=>m.parseWeights(value));});
test('document golden formula uses alpha 4, HCA 2.5 and sigma 10.5 identically for NBA and WNBA',()=>{for(const league of ['NBA','WNBA']){const p=m.projectEfficiency(metrics(),metrics(),league,false);assert.equal(p.home,112.5);assert.equal(p.away,110);assert.equal(p.finalPace,100);assert.equal(p.adjustment,0);assert.equal(p.alpha,4);assert.equal(p.hca,2.5);assert.equal(p.sigma,10.5);const neutral=m.projectEfficiency(metrics(),metrics(),league,true);assert.equal(neutral.home,neutral.away);}});
test('pace weight is applied to final scores; defense adjustment has the correct sign and is zero-sum',()=>{const p=m.projectEfficiency(metrics(),metrics(),'NBA',false,[0,0,0,0,100]);assert.equal(p.finalPace,108);assert.equal(p.home,121.5);assert.equal(p.away,118.8);const d=m.projectEfficiency(metrics({drtg:100}),metrics(),'NBA',true,[0,100,0,0,0]);assert.ok(d.adjustment>0);assert.equal(d.home+d.away,d.baselineHome+d.baselineAway);assert.ok(d.home>d.baselineHome&&d.away<d.baselineAway);});
test('standardized three-point differences are invariant to percent vs proportion scale',()=>{const h=metrics({threePct:.4}),a=metrics();const p=m.projectEfficiency(h,a,'NBA',true,[0,0,100,0,0]),scale=x=>({...x,threePct:x.threePct*100,observations:x.observations.map(r=>({...r,three:r.three*100}))}),q=m.projectEfficiency(scale(h),scale(a),'NBA',true,[0,0,100,0,0]);assert.ok(Math.abs(p.home-q.home)<1e-10);});
test('10,000 normal-margin simulations are deterministic, complementary and close to the one-sigma normal probability',()=>{const r=m.simulateMargin(10.5,10.5,'golden');assert.deepEqual(r,m.simulateMargin(10.5,10.5,'golden'));assert.equal(r.iterations,10000);assert.equal(r.homeWins+r.awayWins,10000);assert.ok(Math.abs(r.home-.8413447)<.015);assert.equal(m.simulateMargin(0,10.5,'golden').home,.5);assert.equal(m.simulateMargin(-10.5,10.5,'golden').home,r.away);assert.ok(r.marginP10<r.marginP50&&r.marginP50<r.marginP90);});
test('all 78 actual box scores reconcile points, teams, leagues and overtime-normalized possessions',()=>{assert.equal(nba.boxes.length+wnba.boxes.length,78);for(const [league,f,minutes] of [['NBA',nba,48],['WNBA',wnba,40]]){for(const b of f.boxes){assert.equal(b.league,league);assert.ok(b.minutes>=minutes);assert.ok(b.possessions>0);}assert.ok(f.boxes.some(b=>b.minutes>minutes));}const b=wnba.boxes[0],expected=([b.home,b.away].reduce((sum,t)=>sum+t.fga+.44*t.fta-t.oreb+t.turnovers,0))/2;assert.equal(b.possessions,expected);});
test('source mismatch, missing stats and inconsistent final points fail closed',()=>{const g=nba.games[0],raw=structuredClone(nba.raw[g.id]);assert.throws(()=>m.parseEfficiencyBox(raw,g,'WNBA'));delete raw.boxscore.teams[0].statistics;assert.throws(()=>m.parseEfficiencyBox(raw,g,'NBA'));assert.throws(()=>m.parseEfficiencyBox(nba.raw[g.id],{...g,homeScore:g.homeScore+1},'NBA'));});
test('both leagues produce document-model rates, correct shared recommendations, and reject missing boxes or stale weights',()=>{for(const [league,f] of [['NBA',nba],['WNBA',wnba]]){const a=m.analyzeEfficiency(f.game,f.history,f.boxes,league,undefined,now);assert.equal(a.status,'ready');assert.equal(a.simulation.sigma,10.5);assert.equal(a.simulation.iterations,10000);assert.equal(a.probabilities.home,a.simulation.homeWins/10000);assert.equal(a.probabilities.home+a.probabilities.away,1);assert.equal(a.inputs.calculation.hca,f.game.neutral?0:2.5);const report={game:f.game,analysis:a,sourceFetchedAt:new Date(now).toISOString()};assert.ok(presentation.readyNbaAnalysis(f.game,report,now,false,m.weightKey([20,20,20,20,20])));assert.equal(presentation.readyNbaAnalysis(f.game,report,now,false,m.weightKey([0,0,0,0,100])),null);const pick=presentation.nbaPick(f.game,a);assert.equal(pick.probability,Math.max(a.probabilities.home,a.probabilities.away));assert.throws(()=>m.analyzeEfficiency(f.game,f.history,f.boxes.slice(1),league,undefined,now));assert.equal(m.analyzeEfficiency({...f.game,state:'live'},f.history,f.boxes,league,undefined,now).status,'waiting');}});
test('failed efficiency source cannot silently fall back to old-score forecasts',async()=>{
 const original=fetch,oldNow=Date.now;Date.now=()=>now;let calls=0;
 globalThis.fetch=async input=>{calls++;const id=new URL(input).searchParams.get('event');if(id===nba.games.at(-1).id)return new Response('',{status:503});return Response.json(nba.raw[id]);};
 try{const source=await import(moduleUrl('lib/basketball-efficiency-source.ts')+'#failure');await assert.rejects(source.efficiencyGameAnalysis(nba.game,nba.history,'NBA'));await new Promise(r=>setImmediate(r));assert.equal(calls,nba.boxes.length);}finally{globalThis.fetch=original;Date.now=oldNow;}
});
