import {test} from 'node:test';
import assert from 'node:assert/strict';
import {moduleUrl} from './profile-loader.mjs';
const {analyzeFootball,footballDistribution,footballForm,footballDay,parseFootballEvents,validFootballDay}=await import(moduleUrl('lib/football.ts'));
const now=Date.parse('2026-09-27T12:00:00Z');
function event(id='100',overrides={}){
 return {id,date:'2026-09-28T19:00:00Z',season:{year:2026},competitions:[{date:'2026-09-28T19:00:00Z',timeValid:true,status:{type:{name:'STATUS_SCHEDULED',state:'pre',completed:false}},competitors:[{homeAway:'home',team:{id:'1',displayName:'Arsenal'},score:'0'},{homeAway:'away',team:{id:'2',displayName:'Chelsea'},score:'0'}],...overrides}]};
}
const match=parseFootballEvents({events:[event()]},'eng.1')[0];
function history(){return Array.from({length:10},(_,i)=>({...match,id:'old'+i,start:new Date(now-(i+2)*86400000).toISOString(),statusName:'STATUS_FULL_TIME',state:'final',home:i%2?match.away:match.home,away:i%2?match.home:match.away,homeScore:2,awayScore:1}));}
test('Taiwan date crosses midnight and strict dates reject rollover',()=>{assert.equal(footballDay('2026-09-28T19:00Z'),'2026-09-29');assert.equal(validFootballDay('2026-02-30'),false);assert.equal(validFootballDay('2026-09-27'),true);});
test('parser hides pregame zero scores, preserves identity and translates names',()=>{assert.equal(match.homeScore,null);assert.equal(match.home.name,'阿森納');assert.equal(match.home.id,'1');assert.equal(match.state,'scheduled');});
test('parser rejects an explicitly different competition from a team feed',()=>{const e=event();e.league={slug:'eng.fa'};assert.equal(parseFootballEvents({events:[e]},'eng.1').length,0);});
test('parser handles numeric-object scores and legitimate zero in a final',()=>{const e=event('1',{status:{type:{name:'STATUS_FULL_TIME',state:'post',completed:true}}});e.competitions[0].competitors[0].score={value:0};e.competitions[0].competitors[1].score={value:2};const g=parseFootballEvents({events:[e]},'eng.1')[0];assert.equal(g.homeScore,0);assert.equal(g.awayScore,2);});
test('missing scores never become 0 and duplicate events are removed',()=>{const e=event('1',{status:{type:{name:'STATUS_FULL_TIME',state:'post',completed:true}}});e.competitions[0].competitors[0].score=null;const rows=parseFootballEvents({events:[e,e]},'eng.1');assert.equal(rows.length,1);assert.equal(rows[0].homeScore,null);});
test('postponed and suspended fixtures are not live or eligible for analysis',()=>{for(const name of ['STATUS_POSTPONED','STATUS_CANCELED','STATUS_SUSPENDED','STATUS_ABANDONED']){const g=parseFootballEvents({events:[event('1',{status:{type:{name,state:'in',completed:false}}})]},'eng.1')[0];assert.equal(g.state,'other');assert.equal(analyzeFootball(g,history(),now).status,'closed');}});
test('unknown kickoff and started games cannot produce predictions',()=>{assert.equal(analyzeFootball({...match,timeConfirmed:false},history(),now).status,'waiting');assert.equal(analyzeFootball({...match,start:new Date(now).toISOString()},history(),now).status,'closed');const e=event('2',{timeValid:false});e.timeValid=true;assert.equal(parseFootballEvents({events:[e]},'eng.1')[0].timeConfirmed,false);});
test('distribution includes draw and totals normalize',()=>{const {probabilities:p,scores}=footballDistribution(1.5,1.5);assert.ok(Math.abs(p.home+p.draw+p.away-1)<1e-10);assert.ok(Math.abs(p.over25+p.under25-1)<1e-10);assert.ok(Math.abs(p.home-p.away)<1e-10);assert.ok(p.draw>0);assert.equal(scores.length,3);assert.ok(scores[0].probability>=scores[1].probability);});
test('under 2.5 agrees with independent Poisson sum',()=>{const h=1.4,a=.9,p=footballDistribution(h,a).probabilities;const expected=Math.exp(-(h+a))*(1+h+a+(h+a)**2/2);assert.ok(Math.abs(p.under25-expected)<1e-10);});
test('future data, extra time, missing scores and older than a year are excluded',()=>{const bad=[{...history()[0],id:'future',start:new Date(now+86400000).toISOString()},{...history()[0],id:'aet',statusName:'STATUS_FINAL_AET'},{...history()[0],id:'pen',statusName:'STATUS_FINAL_PEN'},{...history()[0],id:'missing',awayScore:null},{...history()[0],id:'old',start:'2024-01-01T00:00Z'}];assert.equal(footballForm('1','home',bad,now).games,0);});
test('insufficient and stale history have no invented probabilities',()=>{const short=analyzeFootball(match,history().slice(0,4),now);assert.equal(short.status,'waiting');assert.equal(short.probabilities,undefined);const old=history().map((g,i)=>({...g,start:new Date(now-(140+i)*86400000).toISOString()}));assert.equal(analyzeFootball(match,old,now).status,'waiting');});
test('ready analysis uses distinct 90-minute history and three score scenarios',()=>{const rows=history();const a=analyzeFootball(match,[...rows,...rows],now);assert.equal(a.status,'ready');assert.equal(a.homeForm.games,10);assert.equal(a.scores.length,3);assert.ok(a.expected.home>a.expected.away);assert.match(a.notes.join(''),/基礎模型/);});
test('another league and the target game cannot leak into training',()=>{const rows=history().map(g=>({...g,league:'esp.1'}));assert.equal(analyzeFootball(match,rows,now).status,'waiting');});
test('neutral-site analysis removes venue weighting',()=>{const a=analyzeFootball({...match,neutral:true},history(),now);assert.equal(a.status,'ready');assert.ok(Math.abs(a.expected.home-a.expected.away)<.2);});
